# Generated by Django 5.2 on 2025-05-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_team_teammembership_team_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammembership',
            options={'ordering': ['-joined_at']},
        ),
    ]
