# Generated by Django 5.2 on 2025-06-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'TODO'), ('in_progress', 'In_progress'), ('done', 'Done')], max_length=11),
        ),
    ]
