# Generated by Django 5.2 on 2025-06-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeentry',
            unique_together=set(),
        ),
    ]
