# Generated by Django 5.2 on 2026-06-21 14:30

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_assigned_to_alter_task_status_and_more'),
        ('timetrack', '0002_alter_timeentry_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='minutes',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['user', 'date'], name='timetrack_t_user_id_5ec0d9_idx'),
        ),
    ]
