# Generated by Django 5.2 on 2026-06-21 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_options'),
        ('tasks', '0003_alter_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['task', '-created_at'], name='comments_co_task_id_ef7037_idx'),
        ),
    ]
