# Generated by Django 5.2 on 2025-05-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('task', 'Task'), ('comment', 'Comment'), ('invite', 'Invite')], default='general', max_length=50),
        ),
    ]
